import { type NextPage } from "next";
import Head from "next/head";
import { signIn, signOut, useSession } from "next-auth/react";

import { api } from "../utils/api";
import { Center, Divider, Stack, TextInput, Title } from "@mantine/core";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Games Market</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Stack>
          <Center>
            <Stack>
              <Title order={2} mt={30}>
                Find your favorites games in the lowest price
              </Title>
              <TextInput
                size="lg"
                placeholder="For e.g: The last of us"
              ></TextInput>
              <Divider my="sm" />
            </Stack>
          </Center>
          <AuthShowcase />
        </Stack>
      </main>
    </>
  );
};

export default Home;

const AuthShowcase: React.FC = () => {
  const { data: sessionData } = useSession();

  const { data: secretMessage } = api.example.getSecretMessage.useQuery(
    undefined, // no input
    { enabled: sessionData?.user !== undefined }
  );

  return (
    <div>
      <p>
        {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
        Your role: {sessionData?.user?.role}
        {secretMessage && <span> - {secretMessage}</span>}
      </p>
    </div>
  );
};
